info:
  contact: {}
paths:
  /api/v1/hello:
    get:
      description: Get a friendly greeting
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Say hello
      tags:
      - greeting
swagger: "2.0"
